### PR TITLE
Fix the Skolem trick with GHC ≥ 9.4

### PR DESCRIPTION
**Pull request by ncfavier**
Using a data family instead of a type family weirdly prevents the `Skolem` constructor from being treated as a metavariable, see https://gitlab.haskell.org/ghc/ghc/-/issues/23743#note_522186

Backlog: https://github.com/obsidiansystems/dependent-sum-template/pull/2#issuecomment-1649439589

@ali-abrar @cgibbard

### CODE REVIEW

**Comment by Ericson2314** [comment]
@ncfavier Can you add back the removed tests to "prove it"?

**Comment by Ericson2314** [comment]
Sorry I was really unclear --- add the skipped-over GHC versions (in the cabal file and github actions) to prove it works on them too.

**Comment by ncfavier** [comment]
This should do it, if there's anything else feel free to push directly to this branch.

**Comment by Ericson2314** [comment]
Now there are failures in the older versions? Do we need to conditionally switch between type and data family?

**Comment by ncfavier** [comment]
No I was just confused and undid the wrong thing.

**Comment by ncfavier** [comment]
(This should be good to go.)

**Comment by Ericson2314** [comment]
Published: https://hackage.haskell.org/package/dependent-sum-template-0.2.0.1

Thanks again @ncfavier

**Pull request merged**
