### PR TITLE
GHC 9.6

### PR DESCRIPTION
**Pull request by Ericson2314**

### CODE REVIEW

**Comment by erikd** [comment]
Thanks @Ericson2314 !

**Comment by ncfavier** [comment]
Builds and tests fine with GHC 9.2. GHC 9.4 complains with

```
test/test.hs:159:1: error:
    More than one instance found for GEq (a_0), and unsure what to do. Please report this.
    |
159 | deriveGEq ''Spleeb
    | ^^^^^^^^^^^^^^^^^^
```

**Comment by ncfavier** [comment]
The failing data type is

```hs
data Spleeb a b where
    P :: a Double -> Qux b -> Spleeb a b
```

The difference between versions seems to be that `reifyInstancesWithRigids [a, b] ''GEq a` returns `[]` in GHC 9.2 (which is expected because `a` is a rigid type variable), but with GHC 9.4 it returns 

```hs
InstanceD Nothing [AppT (ConT Data.GADT.Internal.GEq) (VarT a_6989586621679027108),AppT (ConT Data.GADT.Internal.GEq) (VarT b_6989586621679027109)] (AppT (ConT Data.GADT.Internal.GEq) (SigT (AppT (AppT (ConT GHC.Generics.:*:) (VarT a_6989586621679027108)) (VarT b_6989586621679027109)) (AppT (AppT ArrowT (VarT k_6989586621679027107)) StarT))) []
InstanceD Nothing [AppT (ConT Data.GADT.Internal.GEq) (VarT f_6989586621679030688),AppT (ConT Data.GADT.Internal.GEq) (VarT g_6989586621679030689)] (AppT (ConT Data.GADT.Internal.GEq) (SigT (AppT (AppT (ConT GHC.Generics.:+:) (VarT f_6989586621679030688)) (VarT g_6989586621679030689)) (AppT (AppT ArrowT (VarT k_6989586621679030687)) StarT))) []
InstanceD Nothing [] (AppT (ConT Data.GADT.Internal.GEq) (SigT (AppT (ConT Data.Type.Equality.:~:) (VarT a_6989586621679030691)) (AppT (AppT ArrowT (VarT k_6989586621679030690)) StarT))) []
InstanceD Nothing [] (AppT (ConT Data.GADT.Internal.GEq) (SigT (AppT (ConT Data.Type.Equality.:~~:) (VarT a_6989586621679030694)) (AppT (AppT ArrowT (VarT k_6989586621679030693)) StarT))) []
InstanceD Nothing [AppT (ConT Data.GADT.Internal.GEq) (VarT a_6989586621679030696),AppT (ConT Data.GADT.Internal.GEq) (VarT b_6989586621679030697)] (AppT (ConT Data.GADT.Internal.GEq) (SigT (AppT (AppT (ConT Data.Functor.Product.Product) (VarT a_6989586621679030696)) (VarT b_6989586621679030697)) (AppT (AppT ArrowT (VarT k_6989586621679030695)) StarT))) []
InstanceD Nothing [AppT (ConT Data.GADT.Internal.GEq) (VarT a_6989586621679030876),AppT (ConT Data.GADT.Internal.GEq) (VarT b_6989586621679030877)] (AppT (ConT Data.GADT.Internal.GEq) (SigT (AppT (AppT (ConT Data.Functor.Sum.Sum) (VarT a_6989586621679030876)) (VarT b_6989586621679030877)) (AppT (AppT ArrowT (VarT k_6989586621679030875)) StarT))) []
```

So my guess is that GHC 9.4 got smarter, and the `Skolem` trick in https://github.com/obsidiansystems/dependent-sum-template/blob/9a83b0a175ad71be449afb65c3b7900de64fdc0f/src/Data/GADT/TH/Internal.hs#L37-L38 does not trick it any more. @cgibbard any ideas?

**EDIT**: looking at the returned instances, it seems like it only returns the instances that unify with `GEq (s a)`, hence somehow treating `Skolem` as a metavariable. GHC bug?

**Comment by ncfavier** [comment]
Opened a GHC bug with a minimal reproducer https://gitlab.haskell.org/ghc/ghc/-/issues/23743

**Comment by ali-abrar** [comment]
Given the ghc issue, it might be better to support 9.6 and skip 9.2 and 9.4

**Comment by ali-abrar** [comment]
@Ericson2314 if you're ok with the direction of #6, please close this.

**Pull request closed without merging**
